<?php

/**
 * Test class for S2Dao_DaoMetaDataImpl.
 * Generated by PHPUnit2_Util_Skeleton on 2006-05-26 at 22:08:44.
 */
class S2Dao_DaoMetaDataImplTest extends PHPUnit2_Framework_TestCase {

    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        $suite  = new PHPUnit2_Framework_TestSuite("S2Dao_DaoMetaDataImplTest");
        $result = PHPUnit2_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testSetAnnotationReaderFactory().
     */
    public function testSetAnnotationReaderFactory() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testSetResultSetFactory().
     */
    public function testSetResultSetFactory() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testSetStatementFactory().
     */
    public function testSetStatementFactory() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testSetDbms().
     */
    public function testSetDbms() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testSetDataSource().
     */
    public function testSetDataSource() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testSetDaoClass().
     */
    public function testSetDaoClass() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testGetBeanClass().
     */
    public function testGetBeanClass() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testSetBeanClass().
     */
    public function testSetBeanClass() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testGetBeanMetaData().
     */
    public function testGetBeanMetaData() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testGetSqlCommand().
     */
    public function testGetSqlCommand() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testGetDaoInterface().
     */
    public function testGetDaoInterface() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testCreateFindCommand().
     */
    public function testCreateFindCommand() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testCreateFindArrayCommand().
     */
    public function testCreateFindArrayCommand() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testCreateFindBeanCommand().
     */
    public function testCreateFindBeanCommand() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testCreateFindObjectCommand().
     */
    public function testCreateFindObjectCommand() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testHasSqlCommand().
     */
    public function testHasSqlCommand() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }
}

?>