<?php

/**
 * Test class for S2Dao_PagerJsonResultSetWrapper.
 * Generated by PHPUnit2_Util_Skeleton on 2006-07-10 at 01:14:11.
 */
class S2Dao_PagerJsonResultSetWrapperTest extends PHPUnit2_Framework_TestCase {

    private $wrapper = null;

    public static function main() {
        $suite  = new PHPUnit2_Framework_TestSuite("S2Dao_PagerJsonResultSetWrapperTest");
        $result = PHPUnit2_TextUI_TestRunner::run($suite);
    }

    protected function setUp() {
        $this->wrapper = new S2Dao_PagerJsonResultSetWrapper();
    }

    protected function tearDown() {
        $this->wrapper = null;
    }

    public function testFilter() {
        $json = '["aaa", "bbb", "ccc", "ddd", "eee"]';
        $filter_json = '["ccc", "ddd", "eee"]';
        
        $this->condition->setLimit(3);
        $this->condition->setOffset(2);

        $json = $this->wrapper->filter($json, $this->condition);

        $this->assertEquals($json, $filter_json);
    }
}

?>