<?php

/**
 * Test class for S2Dao_PagerYamlResultSetWrapper.
 * Generated by PHPUnit2_Util_Skeleton on 2006-07-10 at 01:14:11.
 */
class S2Dao_PagerYamlResultSetWrapperTest extends PHPUnit2_Framework_TestCase {

    private $wrapper = null;

    public static function main() {
        $suite  = new PHPUnit2_Framework_TestSuite("S2Dao_PagerYamlResultSetWrapperTest");
        $result = PHPUnit2_TextUI_TestRunner::run($suite);
    }

    protected function setUp() {
        $this->wrapper = new S2Dao_PagerYamlResultSetWrapper();
    }

    protected function tearDown() {
        $this->wrapper = null;
    }

    public function testFilter() {
        $yaml = '';
        $filter_yaml = '';

        $this->condition->setLimit(3);
        $this->condition->setOffset(2);

        $yaml = S2Dao_PagerUtil::filterYaml($yaml, $this->condition);

        $this->assertEquals($yaml, $filter_yaml);
    }
}

?>