<?php

/**
 * Test class for S2Dao_PagerResultSetWrapperImpl.
 * Generated by PHPUnit2_Util_Skeleton on 2006-07-10 at 01:14:11.
 */
class S2Dao_PagerResultSetWrapperImplTest extends PHPUnit2_Framework_TestCase {

    private $wrapper = null;

    public static function main() {
        $suite  = new PHPUnit2_Framework_TestSuite("S2Dao_PagerResultSetWrapperImplTest");
        $result = PHPUnit2_TextUI_TestRunner::run($suite);
    }

    protected function setUp() {
        $this->wrapper = new S2Dao_PagerResultSetWrapperImpl();
    }

    protected function tearDown() {
        $this->wrapper = null;
    }

    public function testFilter() {
        $array = array('aaa', 'bbb', 'ccc', 'ddd', 'eee');
        $filter_array = arrary('ccc', 'ddd', 'eee');
        
        $this->condition->setLimit(3);
        $this->condition->setOffset(2);
        
        $array = $this->wrapper->filter($array, $this->condition);
        
        $this->assertEquals($array, $filter_array);
    }
    
    function testFilterS2Dao_ArrayList() {
        $array_data = array('aaa', 'bbb', 'ccc', 'ddd', 'eee');
        $filter_array_data = arrary('ccc', 'ddd', 'eee');
        $list = new S2Dao_ArrayList(new ArrayObject($array_data));
        $filter_list = new S2Dao_ArrayList(new ArrayObject($filter_array_data));
        
        $this->condition->setLimit(3);
        $this->condition->setOffset(2);
        
        $list = $this->wrapper->filter($list, $this->condition);
        
        $this->assertEquals($list, $filter_list);
    }
     
}

?>