<?php

/**
 * Test class for S2Dao_SQLiteDBMetaData.
 * Generated by PHPUnit2_Util_Skeleton on 2006-06-18 at 21:53:06.
 */
class S2Dao_SQLiteDBMetaDataTest extends PHPUnit2_Framework_TestCase {

    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        $suite  = new PHPUnit2_Framework_TestSuite("S2Dao_SQLiteDBMetaDataTest");
        $result = PHPUnit2_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testGetTableInfo().
     */
    public function testGetTableInfo() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }
}

?>