--
-- MySQL TABLE
--
CREATE TABLE SHELF (
    ID INTEGER NOT NULL auto_increment,
    CD_ID INTEGER NOT NULL,
    ADD_TIME DATETIME DEFAULT '2005-12-25 10:12:13',
    PRIMARY KEY(ID,CD_ID),
    FOREIGN KEY(CD_ID) REFERENCES CD(ID)
);
