<?php

/**
 * Test class for S2Dao_BeanJsonMetaDataResultSetHandler.
 * Generated by PHPUnit2_Util_Skeleton on 2006-06-18 at 21:53:06.
 */
class S2Dao_BeanJsonMetaDataResultSetHandlerTest extends PHPUnit2_Framework_TestCase {

    public static function main() {
        $suite  = new PHPUnit2_Framework_TestSuite("S2Dao_BeanJsonMetaDataResultSetHandlerTest");
        $result = PHPUnit2_TextUI_TestRunner::run($suite);
    }

    protected function setUp() {
    }

    protected function tearDown() {
    }

    public function testHandle() {
    }
}

?>